import sqlite3
import os


class library(object):
    # Define the parameters to local the .lib file and .db file
    _library_list = ('lib_file', 'db_file')

    def __init__(self):
        # generate a libaray object
        self.lib_content = {item: '' for item in self._library_list}

    def _connect_lib2db(self, file_path=''):
        # connect the library to the datebase file
        db_lib = sqlite3.connect(file_path)
        return db_lib

    def _connect_lib2bib(self, file_path=''):
        # connect the library to bib file
        if ~os.path.isfile(file_path):   # if the file is not exist
            pass
        try:
            with open(file_path, encoding='utf-8') as bib_file:
                self.lib_content['lib_file'] = bib_file
        except OSError as err:
            print('can not load bibtex file, nothing is generated')
            print('OS error: {0}'.format(err))


# -------------------------- Think about this --------------------------- #
def init_lib(bib_name=''):
    """ Set the bib library path """
    lib_obj = library()
    if os.path.isfile(bib_name+'.bib'):
        lib_obj.lib_name = bib_name
    else:
        sig = input('File is not exit\n Creat?\t y/n')
    if sig == 'y':
        lib = open(bib_name+'.bib', 'w+', encoding='utf-8')
        lib.write('#This file is generated by Reference Manager\n')
        lib.write('#UTF-8 coding\n################### \n')
        lib_obj._lib_name = bib_name
        lib.close()
    return lib_obj


def add_2_lib(bib_obj=bibitem(), lib_obj=library()):
    """ add the bibtex obj into library obj. """
    # need to check if there are the same item
    # assume the file is exist
    pass
